// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Dismissal struct {
	ID               string    `json:"id"`
	UserID           string    `json:"user_id"`
	TriggeredEventID string    `json:"triggered_event_id"`
	DismissedAt      time.Time `json:"dismissed_at"`
	Type             string    `json:"type"`
}

type Event struct {
	ID               string         `json:"id"`
	OfferID          string         `json:"offer_id"`
	TeamID           string         `json:"team_id"`
	TeamName         string         `json:"team_name"`
	League           string         `json:"league"`
	TeamColor        sql.NullString `json:"team_color"`
	Icon             sql.NullString `json:"icon"`
	PartnerName      string         `json:"partner_name"`
	OfferName        string         `json:"offer_name"`
	OfferDescription string         `json:"offer_description"`
	TriggerCondition string         `json:"trigger_condition"`
	TriggerRule      sql.NullString `json:"trigger_rule"`
	RegionCode       sql.NullString `json:"region_code"`
	OfferUrl         sql.NullString `json:"offer_url"`
	AffiliateUrl     sql.NullString `json:"affiliate_url"`
	AffiliateTagline sql.NullString `json:"affiliate_tagline"`
	IsActive         int64          `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type FeatureFlag struct {
	Key       string    `json:"key"`
	Enabled   int64     `json:"enabled"`
	UpdatedAt time.Time `json:"updated_at"`
}

type League struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	Icon         string    `json:"icon"`
	DisplayOrder int64     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type Notification struct {
	ID               string    `json:"id"`
	UserID           string    `json:"user_id"`
	TriggeredEventID string    `json:"triggered_event_id"`
	SentAt           time.Time `json:"sent_at"`
	Status           string    `json:"status"`
}

type ScreenBlock struct {
	ID        string    `json:"id"`
	Screen    string    `json:"screen"`
	Type      string    `json:"type"`
	Key       string    `json:"key"`
	Position  int64     `json:"position"`
	Enabled   int64     `json:"enabled"`
	Config    string    `json:"config"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Subscription struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	EventID   string    `json:"event_id"`
	CreatedAt time.Time `json:"created_at"`
}

type TriggeredEvent struct {
	ID          string         `json:"id"`
	EventID     string         `json:"event_id"`
	GameID      sql.NullString `json:"game_id"`
	TriggeredAt time.Time      `json:"triggered_at"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	Payload     sql.NullString `json:"payload"`
}

type User struct {
	ID        string         `json:"id"`
	DeviceID  string         `json:"device_id"`
	PushToken sql.NullString `json:"push_token"`
	Platform  string         `json:"platform"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Token     sql.NullString `json:"token"`
}
