// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const backfillTeamSubscriptions = `-- name: BackfillTeamSubscriptions :exec
INSERT OR IGNORE INTO subscriptions (id, user_id, event_id)
SELECT
    lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6))) as id,
    s.user_id,
    e.id as event_id
FROM events e
JOIN (
    SELECT DISTINCT sub.user_id, ev.team_id
    FROM subscriptions sub
    JOIN events ev ON sub.event_id = ev.id
) s ON s.team_id = e.team_id
LEFT JOIN subscriptions existing ON existing.user_id = s.user_id AND existing.event_id = e.id
WHERE e.is_active = 1
  AND existing.id IS NULL
`

func (q *Queries) BackfillTeamSubscriptions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, backfillTeamSubscriptions)
	return err
}

const clearPushToken = `-- name: ClearPushToken :exec
UPDATE users SET push_token = NULL, updated_at = CURRENT_TIMESTAMP
WHERE push_token = ? AND id != ?
`

type ClearPushTokenParams struct {
	PushToken sql.NullString `json:"push_token"`
	ID        string         `json:"id"`
}

func (q *Queries) ClearPushToken(ctx context.Context, arg ClearPushTokenParams) error {
	_, err := q.db.ExecContext(ctx, clearPushToken, arg.PushToken, arg.ID)
	return err
}

const countUserClaimedDeals = `-- name: CountUserClaimedDeals :one
SELECT COUNT(*) as count FROM dismissals WHERE user_id = ? AND type = 'got_it'
`

func (q *Queries) CountUserClaimedDeals(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserClaimedDeals, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserSubscriptions = `-- name: CountUserSubscriptions :one
SELECT COUNT(*) as count FROM subscriptions WHERE user_id = ?
`

func (q *Queries) CountUserSubscriptions(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserSubscriptions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDismissal = `-- name: CreateDismissal :one
INSERT INTO dismissals (id, user_id, triggered_event_id, type)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, triggered_event_id, dismissed_at, type
`

type CreateDismissalParams struct {
	ID               string `json:"id"`
	UserID           string `json:"user_id"`
	TriggeredEventID string `json:"triggered_event_id"`
	Type             string `json:"type"`
}

func (q *Queries) CreateDismissal(ctx context.Context, arg CreateDismissalParams) (Dismissal, error) {
	row := q.db.QueryRowContext(ctx, createDismissal,
		arg.ID,
		arg.UserID,
		arg.TriggeredEventID,
		arg.Type,
	)
	var i Dismissal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TriggeredEventID,
		&i.DismissedAt,
		&i.Type,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, offer_id, team_id, team_name, league, team_color, icon, partner_name, offer_name, offer_description, trigger_condition, trigger_rule, region_code, offer_url, affiliate_url, affiliate_tagline, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, offer_id, team_id, team_name, league, team_color, icon, partner_name, offer_name, offer_description, trigger_condition, trigger_rule, region_code, offer_url, affiliate_url, affiliate_tagline, is_active, created_at, updated_at
`

type CreateEventParams struct {
	ID               string         `json:"id"`
	OfferID          string         `json:"offer_id"`
	TeamID           string         `json:"team_id"`
	TeamName         string         `json:"team_name"`
	League           string         `json:"league"`
	TeamColor        sql.NullString `json:"team_color"`
	Icon             sql.NullString `json:"icon"`
	PartnerName      string         `json:"partner_name"`
	OfferName        string         `json:"offer_name"`
	OfferDescription string         `json:"offer_description"`
	TriggerCondition string         `json:"trigger_condition"`
	TriggerRule      sql.NullString `json:"trigger_rule"`
	RegionCode       sql.NullString `json:"region_code"`
	OfferUrl         sql.NullString `json:"offer_url"`
	AffiliateUrl     sql.NullString `json:"affiliate_url"`
	AffiliateTagline sql.NullString `json:"affiliate_tagline"`
	IsActive         int64          `json:"is_active"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.OfferID,
		arg.TeamID,
		arg.TeamName,
		arg.League,
		arg.TeamColor,
		arg.Icon,
		arg.PartnerName,
		arg.OfferName,
		arg.OfferDescription,
		arg.TriggerCondition,
		arg.TriggerRule,
		arg.RegionCode,
		arg.OfferUrl,
		arg.AffiliateUrl,
		arg.AffiliateTagline,
		arg.IsActive,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.TeamID,
		&i.TeamName,
		&i.League,
		&i.TeamColor,
		&i.Icon,
		&i.PartnerName,
		&i.OfferName,
		&i.OfferDescription,
		&i.TriggerCondition,
		&i.TriggerRule,
		&i.RegionCode,
		&i.OfferUrl,
		&i.AffiliateUrl,
		&i.AffiliateTagline,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLeague = `-- name: CreateLeague :one
INSERT INTO leagues (id, name, icon, display_order)
VALUES (?, ?, ?, ?)
RETURNING id, name, icon, display_order, created_at
`

type CreateLeagueParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Icon         string `json:"icon"`
	DisplayOrder int64  `json:"display_order"`
}

func (q *Queries) CreateLeague(ctx context.Context, arg CreateLeagueParams) (League, error) {
	row := q.db.QueryRowContext(ctx, createLeague,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.DisplayOrder,
	)
	var i League
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, user_id, triggered_event_id, status)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, triggered_event_id, sent_at, status
`

type CreateNotificationParams struct {
	ID               string `json:"id"`
	UserID           string `json:"user_id"`
	TriggeredEventID string `json:"triggered_event_id"`
	Status           string `json:"status"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.TriggeredEventID,
		arg.Status,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TriggeredEventID,
		&i.SentAt,
		&i.Status,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (id, user_id, event_id)
VALUES (?, ?, ?)
RETURNING id, user_id, event_id, created_at
`

type CreateSubscriptionParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription, arg.ID, arg.UserID, arg.EventID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const createTriggeredEvent = `-- name: CreateTriggeredEvent :one
INSERT INTO triggered_events (id, event_id, game_id, expires_at, payload)
VALUES (?, ?, ?, ?, ?)
RETURNING id, event_id, game_id, triggered_at, expires_at, payload
`

type CreateTriggeredEventParams struct {
	ID        string         `json:"id"`
	EventID   string         `json:"event_id"`
	GameID    sql.NullString `json:"game_id"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
	Payload   sql.NullString `json:"payload"`
}

func (q *Queries) CreateTriggeredEvent(ctx context.Context, arg CreateTriggeredEventParams) (TriggeredEvent, error) {
	row := q.db.QueryRowContext(ctx, createTriggeredEvent,
		arg.ID,
		arg.EventID,
		arg.GameID,
		arg.ExpiresAt,
		arg.Payload,
	)
	var i TriggeredEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GameID,
		&i.TriggeredAt,
		&i.ExpiresAt,
		&i.Payload,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, device_id, push_token, platform, token)
VALUES (?, ?, ?, ?, ?)
RETURNING id, device_id, push_token, platform, created_at, updated_at, token
`

type CreateUserParams struct {
	ID        string         `json:"id"`
	DeviceID  string         `json:"device_id"`
	PushToken sql.NullString `json:"push_token"`
	Platform  string         `json:"platform"`
	Token     sql.NullString `json:"token"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.DeviceID,
		arg.PushToken,
		arg.Platform,
		arg.Token,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.PushToken,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
	)
	return i, err
}

const deleteDismissal = `-- name: DeleteDismissal :exec
DELETE FROM dismissals WHERE user_id = ? AND triggered_event_id = ?
`

type DeleteDismissalParams struct {
	UserID           string `json:"user_id"`
	TriggeredEventID string `json:"triggered_event_id"`
}

func (q *Queries) DeleteDismissal(ctx context.Context, arg DeleteDismissalParams) error {
	_, err := q.db.ExecContext(ctx, deleteDismissal, arg.UserID, arg.TriggeredEventID)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE user_id = ? AND event_id = ?
`

type DeleteSubscriptionParams struct {
	UserID  string `json:"user_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, arg.UserID, arg.EventID)
	return err
}

const getDismissal = `-- name: GetDismissal :one
SELECT id, user_id, triggered_event_id, dismissed_at, type FROM dismissals WHERE user_id = ? AND triggered_event_id = ? LIMIT 1
`

type GetDismissalParams struct {
	UserID           string `json:"user_id"`
	TriggeredEventID string `json:"triggered_event_id"`
}

func (q *Queries) GetDismissal(ctx context.Context, arg GetDismissalParams) (Dismissal, error) {
	row := q.db.QueryRowContext(ctx, getDismissal, arg.UserID, arg.TriggeredEventID)
	var i Dismissal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TriggeredEventID,
		&i.DismissedAt,
		&i.Type,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, offer_id, team_id, team_name, league, team_color, icon, partner_name, offer_name, offer_description, trigger_condition, trigger_rule, region_code, offer_url, affiliate_url, affiliate_tagline, is_active, created_at, updated_at FROM events WHERE id = ? LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.TeamID,
		&i.TeamName,
		&i.League,
		&i.TeamColor,
		&i.Icon,
		&i.PartnerName,
		&i.OfferName,
		&i.OfferDescription,
		&i.TriggerCondition,
		&i.TriggerRule,
		&i.RegionCode,
		&i.OfferUrl,
		&i.AffiliateUrl,
		&i.AffiliateTagline,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeague = `-- name: GetLeague :one
SELECT id, name, icon, display_order, created_at FROM leagues WHERE id = ? LIMIT 1
`

func (q *Queries) GetLeague(ctx context.Context, id string) (League, error) {
	row := q.db.QueryRowContext(ctx, getLeague, id)
	var i League
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, user_id, event_id, created_at FROM subscriptions WHERE user_id = ? AND event_id = ? LIMIT 1
`

type GetSubscriptionParams struct {
	UserID  string `json:"user_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, arg.UserID, arg.EventID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getTriggeredEvent = `-- name: GetTriggeredEvent :one
SELECT te.id, te.event_id, te.game_id, te.triggered_at, te.expires_at, te.payload, e.id, e.offer_id, e.team_id, e.team_name, e.league, e.team_color, e.icon, e.partner_name, e.offer_name, e.offer_description, e.trigger_condition, e.trigger_rule, e.region_code, e.offer_url, e.affiliate_url, e.affiliate_tagline, e.is_active, e.created_at, e.updated_at
FROM triggered_events te
JOIN events e ON te.event_id = e.id
WHERE te.id = ?
`

type GetTriggeredEventRow struct {
	ID               string         `json:"id"`
	EventID          string         `json:"event_id"`
	GameID           sql.NullString `json:"game_id"`
	TriggeredAt      time.Time      `json:"triggered_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	Payload          sql.NullString `json:"payload"`
	ID_2             string         `json:"id_2"`
	OfferID          string         `json:"offer_id"`
	TeamID           string         `json:"team_id"`
	TeamName         string         `json:"team_name"`
	League           string         `json:"league"`
	TeamColor        sql.NullString `json:"team_color"`
	Icon             sql.NullString `json:"icon"`
	PartnerName      string         `json:"partner_name"`
	OfferName        string         `json:"offer_name"`
	OfferDescription string         `json:"offer_description"`
	TriggerCondition string         `json:"trigger_condition"`
	TriggerRule      sql.NullString `json:"trigger_rule"`
	RegionCode       sql.NullString `json:"region_code"`
	OfferUrl         sql.NullString `json:"offer_url"`
	AffiliateUrl     sql.NullString `json:"affiliate_url"`
	AffiliateTagline sql.NullString `json:"affiliate_tagline"`
	IsActive         int64          `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) GetTriggeredEvent(ctx context.Context, id string) (GetTriggeredEventRow, error) {
	row := q.db.QueryRowContext(ctx, getTriggeredEvent, id)
	var i GetTriggeredEventRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GameID,
		&i.TriggeredAt,
		&i.ExpiresAt,
		&i.Payload,
		&i.ID_2,
		&i.OfferID,
		&i.TeamID,
		&i.TeamName,
		&i.League,
		&i.TeamColor,
		&i.Icon,
		&i.PartnerName,
		&i.OfferName,
		&i.OfferDescription,
		&i.TriggerCondition,
		&i.TriggerRule,
		&i.RegionCode,
		&i.OfferUrl,
		&i.AffiliateUrl,
		&i.AffiliateTagline,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTriggeredEventByGameID = `-- name: GetTriggeredEventByGameID :one
SELECT id, event_id, game_id, triggered_at, expires_at, payload FROM triggered_events
WHERE event_id = ? AND game_id = ?
LIMIT 1
`

type GetTriggeredEventByGameIDParams struct {
	EventID string         `json:"event_id"`
	GameID  sql.NullString `json:"game_id"`
}

func (q *Queries) GetTriggeredEventByGameID(ctx context.Context, arg GetTriggeredEventByGameIDParams) (TriggeredEvent, error) {
	row := q.db.QueryRowContext(ctx, getTriggeredEventByGameID, arg.EventID, arg.GameID)
	var i TriggeredEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GameID,
		&i.TriggeredAt,
		&i.ExpiresAt,
		&i.Payload,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, device_id, push_token, platform, created_at, updated_at, token FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.PushToken,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
	)
	return i, err
}

const getUserByDeviceID = `-- name: GetUserByDeviceID :one
SELECT id, device_id, push_token, platform, created_at, updated_at, token FROM users WHERE device_id = ? LIMIT 1
`

func (q *Queries) GetUserByDeviceID(ctx context.Context, deviceID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByDeviceID, deviceID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.PushToken,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
	)
	return i, err
}

const getUserByToken = `-- name: GetUserByToken :one
SELECT id, device_id, push_token, platform, created_at, updated_at, token FROM users WHERE token = ? LIMIT 1
`

func (q *Queries) GetUserByToken(ctx context.Context, token sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.PushToken,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
	)
	return i, err
}

const listActiveEvents = `-- name: ListActiveEvents :many
SELECT id, offer_id, team_id, team_name, league, team_color, icon, partner_name, offer_name, offer_description, trigger_condition, trigger_rule, region_code, offer_url, affiliate_url, affiliate_tagline, is_active, created_at, updated_at FROM events WHERE is_active = 1 ORDER BY created_at DESC
`

func (q *Queries) ListActiveEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listActiveEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.TeamID,
			&i.TeamName,
			&i.League,
			&i.TeamColor,
			&i.Icon,
			&i.PartnerName,
			&i.OfferName,
			&i.OfferDescription,
			&i.TriggerCondition,
			&i.TriggerRule,
			&i.RegionCode,
			&i.OfferUrl,
			&i.AffiliateUrl,
			&i.AffiliateTagline,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTriggeredEvents = `-- name: ListActiveTriggeredEvents :many
SELECT te.id, te.event_id, te.game_id, te.triggered_at, te.expires_at, te.payload, e.id, e.offer_id, e.team_id, e.team_name, e.league, e.team_color, e.icon, e.partner_name, e.offer_name, e.offer_description, e.trigger_condition, e.trigger_rule, e.region_code, e.offer_url, e.affiliate_url, e.affiliate_tagline, e.is_active, e.created_at, e.updated_at
FROM triggered_events te
JOIN events e ON te.event_id = e.id
WHERE datetime(te.expires_at) > datetime('now')
ORDER BY te.expires_at ASC
`

type ListActiveTriggeredEventsRow struct {
	ID               string         `json:"id"`
	EventID          string         `json:"event_id"`
	GameID           sql.NullString `json:"game_id"`
	TriggeredAt      time.Time      `json:"triggered_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	Payload          sql.NullString `json:"payload"`
	ID_2             string         `json:"id_2"`
	OfferID          string         `json:"offer_id"`
	TeamID           string         `json:"team_id"`
	TeamName         string         `json:"team_name"`
	League           string         `json:"league"`
	TeamColor        sql.NullString `json:"team_color"`
	Icon             sql.NullString `json:"icon"`
	PartnerName      string         `json:"partner_name"`
	OfferName        string         `json:"offer_name"`
	OfferDescription string         `json:"offer_description"`
	TriggerCondition string         `json:"trigger_condition"`
	TriggerRule      sql.NullString `json:"trigger_rule"`
	RegionCode       sql.NullString `json:"region_code"`
	OfferUrl         sql.NullString `json:"offer_url"`
	AffiliateUrl     sql.NullString `json:"affiliate_url"`
	AffiliateTagline sql.NullString `json:"affiliate_tagline"`
	IsActive         int64          `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) ListActiveTriggeredEvents(ctx context.Context) ([]ListActiveTriggeredEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTriggeredEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTriggeredEventsRow{}
	for rows.Next() {
		var i ListActiveTriggeredEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.GameID,
			&i.TriggeredAt,
			&i.ExpiresAt,
			&i.Payload,
			&i.ID_2,
			&i.OfferID,
			&i.TeamID,
			&i.TeamName,
			&i.League,
			&i.TeamColor,
			&i.Icon,
			&i.PartnerName,
			&i.OfferName,
			&i.OfferDescription,
			&i.TriggerCondition,
			&i.TriggerRule,
			&i.RegionCode,
			&i.OfferUrl,
			&i.AffiliateUrl,
			&i.AffiliateTagline,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTriggeredEventsForUser = `-- name: ListActiveTriggeredEventsForUser :many
SELECT te.id, te.event_id, te.game_id, te.triggered_at, te.expires_at, te.payload, e.id, e.offer_id, e.team_id, e.team_name, e.league, e.team_color, e.icon, e.partner_name, e.offer_name, e.offer_description, e.trigger_condition, e.trigger_rule, e.region_code, e.offer_url, e.affiliate_url, e.affiliate_tagline, e.is_active, e.created_at, e.updated_at,
    CASE WHEN d.id IS NOT NULL THEN 1 ELSE 0 END as is_dismissed,
    d.type as dismissal_type
FROM triggered_events te
JOIN events e ON te.event_id = e.id
JOIN subscriptions s ON s.event_id = e.id AND s.user_id = ?
LEFT JOIN dismissals d ON d.triggered_event_id = te.id AND d.user_id = ?
WHERE datetime(te.expires_at) > datetime('now')
ORDER BY te.expires_at ASC
`

type ListActiveTriggeredEventsForUserParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

type ListActiveTriggeredEventsForUserRow struct {
	ID               string         `json:"id"`
	EventID          string         `json:"event_id"`
	GameID           sql.NullString `json:"game_id"`
	TriggeredAt      time.Time      `json:"triggered_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	Payload          sql.NullString `json:"payload"`
	ID_2             string         `json:"id_2"`
	OfferID          string         `json:"offer_id"`
	TeamID           string         `json:"team_id"`
	TeamName         string         `json:"team_name"`
	League           string         `json:"league"`
	TeamColor        sql.NullString `json:"team_color"`
	Icon             sql.NullString `json:"icon"`
	PartnerName      string         `json:"partner_name"`
	OfferName        string         `json:"offer_name"`
	OfferDescription string         `json:"offer_description"`
	TriggerCondition string         `json:"trigger_condition"`
	TriggerRule      sql.NullString `json:"trigger_rule"`
	RegionCode       sql.NullString `json:"region_code"`
	OfferUrl         sql.NullString `json:"offer_url"`
	AffiliateUrl     sql.NullString `json:"affiliate_url"`
	AffiliateTagline sql.NullString `json:"affiliate_tagline"`
	IsActive         int64          `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	IsDismissed      int64          `json:"is_dismissed"`
	DismissalType    sql.NullString `json:"dismissal_type"`
}

func (q *Queries) ListActiveTriggeredEventsForUser(ctx context.Context, arg ListActiveTriggeredEventsForUserParams) ([]ListActiveTriggeredEventsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTriggeredEventsForUser, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTriggeredEventsForUserRow{}
	for rows.Next() {
		var i ListActiveTriggeredEventsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.GameID,
			&i.TriggeredAt,
			&i.ExpiresAt,
			&i.Payload,
			&i.ID_2,
			&i.OfferID,
			&i.TeamID,
			&i.TeamName,
			&i.League,
			&i.TeamColor,
			&i.Icon,
			&i.PartnerName,
			&i.OfferName,
			&i.OfferDescription,
			&i.TriggerCondition,
			&i.TriggerRule,
			&i.RegionCode,
			&i.OfferUrl,
			&i.AffiliateUrl,
			&i.AffiliateTagline,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDismissed,
			&i.DismissalType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEnabledScreenBlocks = `-- name: ListAllEnabledScreenBlocks :many
SELECT id, screen, type, "key", position, enabled, config, created_at, updated_at FROM screen_blocks
WHERE enabled = 1
ORDER BY screen, position ASC
`

func (q *Queries) ListAllEnabledScreenBlocks(ctx context.Context) ([]ScreenBlock, error) {
	rows, err := q.db.QueryContext(ctx, listAllEnabledScreenBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScreenBlock{}
	for rows.Next() {
		var i ScreenBlock
		if err := rows.Scan(
			&i.ID,
			&i.Screen,
			&i.Type,
			&i.Key,
			&i.Position,
			&i.Enabled,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, device_id, push_token, platform, created_at, updated_at, token FROM users
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.PushToken,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventSubscribers = `-- name: ListEventSubscribers :many
SELECT s.id, s.user_id, s.event_id, s.created_at, u.id, u.device_id, u.push_token, u.platform, u.created_at, u.updated_at, u.token
FROM subscriptions s
JOIN users u ON s.user_id = u.id
WHERE s.event_id = ?
`

type ListEventSubscribersRow struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	EventID     string         `json:"event_id"`
	CreatedAt   time.Time      `json:"created_at"`
	ID_2        string         `json:"id_2"`
	DeviceID    string         `json:"device_id"`
	PushToken   sql.NullString `json:"push_token"`
	Platform    string         `json:"platform"`
	CreatedAt_2 time.Time      `json:"created_at_2"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Token       sql.NullString `json:"token"`
}

func (q *Queries) ListEventSubscribers(ctx context.Context, eventID string) ([]ListEventSubscribersRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventSubscribers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventSubscribersRow{}
	for rows.Next() {
		var i ListEventSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CreatedAt,
			&i.ID_2,
			&i.DeviceID,
			&i.PushToken,
			&i.Platform,
			&i.CreatedAt_2,
			&i.UpdatedAt,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, offer_id, team_id, team_name, league, team_color, icon, partner_name, offer_name, offer_description, trigger_condition, trigger_rule, region_code, offer_url, affiliate_url, affiliate_tagline, is_active, created_at, updated_at FROM events ORDER BY created_at DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.TeamID,
			&i.TeamName,
			&i.League,
			&i.TeamColor,
			&i.Icon,
			&i.PartnerName,
			&i.OfferName,
			&i.OfferDescription,
			&i.TriggerCondition,
			&i.TriggerRule,
			&i.RegionCode,
			&i.OfferUrl,
			&i.AffiliateUrl,
			&i.AffiliateTagline,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringTriggeredEvents = `-- name: ListExpiringTriggeredEvents :many
SELECT te.id, te.event_id, te.game_id, te.triggered_at, te.expires_at, te.payload, e.id, e.offer_id, e.team_id, e.team_name, e.league, e.team_color, e.icon, e.partner_name, e.offer_name, e.offer_description, e.trigger_condition, e.trigger_rule, e.region_code, e.offer_url, e.affiliate_url, e.affiliate_tagline, e.is_active, e.created_at, e.updated_at
FROM triggered_events te
JOIN events e ON te.event_id = e.id
WHERE datetime(te.expires_at) > datetime('now')
  AND datetime(te.expires_at) <= datetime('now', '+' || ? || ' hours')
ORDER BY te.expires_at ASC
`

type ListExpiringTriggeredEventsRow struct {
	ID               string         `json:"id"`
	EventID          string         `json:"event_id"`
	GameID           sql.NullString `json:"game_id"`
	TriggeredAt      time.Time      `json:"triggered_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	Payload          sql.NullString `json:"payload"`
	ID_2             string         `json:"id_2"`
	OfferID          string         `json:"offer_id"`
	TeamID           string         `json:"team_id"`
	TeamName         string         `json:"team_name"`
	League           string         `json:"league"`
	TeamColor        sql.NullString `json:"team_color"`
	Icon             sql.NullString `json:"icon"`
	PartnerName      string         `json:"partner_name"`
	OfferName        string         `json:"offer_name"`
	OfferDescription string         `json:"offer_description"`
	TriggerCondition string         `json:"trigger_condition"`
	TriggerRule      sql.NullString `json:"trigger_rule"`
	RegionCode       sql.NullString `json:"region_code"`
	OfferUrl         sql.NullString `json:"offer_url"`
	AffiliateUrl     sql.NullString `json:"affiliate_url"`
	AffiliateTagline sql.NullString `json:"affiliate_tagline"`
	IsActive         int64          `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) ListExpiringTriggeredEvents(ctx context.Context, dollar_1 sql.NullString) ([]ListExpiringTriggeredEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringTriggeredEvents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringTriggeredEventsRow{}
	for rows.Next() {
		var i ListExpiringTriggeredEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.GameID,
			&i.TriggeredAt,
			&i.ExpiresAt,
			&i.Payload,
			&i.ID_2,
			&i.OfferID,
			&i.TeamID,
			&i.TeamName,
			&i.League,
			&i.TeamColor,
			&i.Icon,
			&i.PartnerName,
			&i.OfferName,
			&i.OfferDescription,
			&i.TriggerCondition,
			&i.TriggerRule,
			&i.RegionCode,
			&i.OfferUrl,
			&i.AffiliateUrl,
			&i.AffiliateTagline,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT "key", enabled, updated_at FROM feature_flags ORDER BY key
`

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.QueryContext(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureFlag{}
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(&i.Key, &i.Enabled, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeagues = `-- name: ListLeagues :many
SELECT id, name, icon, display_order, created_at FROM leagues ORDER BY display_order ASC
`

func (q *Queries) ListLeagues(ctx context.Context) ([]League, error) {
	rows, err := q.db.QueryContext(ctx, listLeagues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []League{}
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNotifications = `-- name: ListPendingNotifications :many
SELECT n.id, n.user_id, n.triggered_event_id, n.sent_at, n.status, u.push_token, u.platform
FROM notifications n
JOIN users u ON n.user_id = u.id
WHERE n.status = 'pending'
`

type ListPendingNotificationsRow struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	TriggeredEventID string         `json:"triggered_event_id"`
	SentAt           time.Time      `json:"sent_at"`
	Status           string         `json:"status"`
	PushToken        sql.NullString `json:"push_token"`
	Platform         string         `json:"platform"`
}

func (q *Queries) ListPendingNotifications(ctx context.Context) ([]ListPendingNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingNotificationsRow{}
	for rows.Next() {
		var i ListPendingNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TriggeredEventID,
			&i.SentAt,
			&i.Status,
			&i.PushToken,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggeredEvents = `-- name: ListTriggeredEvents :many
SELECT te.id, te.event_id, te.game_id, te.triggered_at, te.expires_at, te.payload, e.id, e.offer_id, e.team_id, e.team_name, e.league, e.team_color, e.icon, e.partner_name, e.offer_name, e.offer_description, e.trigger_condition, e.trigger_rule, e.region_code, e.offer_url, e.affiliate_url, e.affiliate_tagline, e.is_active, e.created_at, e.updated_at
FROM triggered_events te
JOIN events e ON te.event_id = e.id
ORDER BY te.triggered_at DESC
LIMIT ?
`

type ListTriggeredEventsRow struct {
	ID               string         `json:"id"`
	EventID          string         `json:"event_id"`
	GameID           sql.NullString `json:"game_id"`
	TriggeredAt      time.Time      `json:"triggered_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	Payload          sql.NullString `json:"payload"`
	ID_2             string         `json:"id_2"`
	OfferID          string         `json:"offer_id"`
	TeamID           string         `json:"team_id"`
	TeamName         string         `json:"team_name"`
	League           string         `json:"league"`
	TeamColor        sql.NullString `json:"team_color"`
	Icon             sql.NullString `json:"icon"`
	PartnerName      string         `json:"partner_name"`
	OfferName        string         `json:"offer_name"`
	OfferDescription string         `json:"offer_description"`
	TriggerCondition string         `json:"trigger_condition"`
	TriggerRule      sql.NullString `json:"trigger_rule"`
	RegionCode       sql.NullString `json:"region_code"`
	OfferUrl         sql.NullString `json:"offer_url"`
	AffiliateUrl     sql.NullString `json:"affiliate_url"`
	AffiliateTagline sql.NullString `json:"affiliate_tagline"`
	IsActive         int64          `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) ListTriggeredEvents(ctx context.Context, limit int64) ([]ListTriggeredEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTriggeredEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTriggeredEventsRow{}
	for rows.Next() {
		var i ListTriggeredEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.GameID,
			&i.TriggeredAt,
			&i.ExpiresAt,
			&i.Payload,
			&i.ID_2,
			&i.OfferID,
			&i.TeamID,
			&i.TeamName,
			&i.League,
			&i.TeamColor,
			&i.Icon,
			&i.PartnerName,
			&i.OfferName,
			&i.OfferDescription,
			&i.TriggerCondition,
			&i.TriggerRule,
			&i.RegionCode,
			&i.OfferUrl,
			&i.AffiliateUrl,
			&i.AffiliateTagline,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT s.id, s.user_id, s.event_id, s.created_at, e.id, e.offer_id, e.team_id, e.team_name, e.league, e.team_color, e.icon, e.partner_name, e.offer_name, e.offer_description, e.trigger_condition, e.trigger_rule, e.region_code, e.offer_url, e.affiliate_url, e.affiliate_tagline, e.is_active, e.created_at, e.updated_at
FROM subscriptions s
JOIN events e ON s.event_id = e.id
WHERE s.user_id = ?
ORDER BY s.created_at DESC
`

type ListUserSubscriptionsRow struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	EventID          string         `json:"event_id"`
	CreatedAt        time.Time      `json:"created_at"`
	ID_2             string         `json:"id_2"`
	OfferID          string         `json:"offer_id"`
	TeamID           string         `json:"team_id"`
	TeamName         string         `json:"team_name"`
	League           string         `json:"league"`
	TeamColor        sql.NullString `json:"team_color"`
	Icon             sql.NullString `json:"icon"`
	PartnerName      string         `json:"partner_name"`
	OfferName        string         `json:"offer_name"`
	OfferDescription string         `json:"offer_description"`
	TriggerCondition string         `json:"trigger_condition"`
	TriggerRule      sql.NullString `json:"trigger_rule"`
	RegionCode       sql.NullString `json:"region_code"`
	OfferUrl         sql.NullString `json:"offer_url"`
	AffiliateUrl     sql.NullString `json:"affiliate_url"`
	AffiliateTagline sql.NullString `json:"affiliate_tagline"`
	IsActive         int64          `json:"is_active"`
	CreatedAt_2      time.Time      `json:"created_at_2"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) ListUserSubscriptions(ctx context.Context, userID string) ([]ListUserSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSubscriptionsRow{}
	for rows.Next() {
		var i ListUserSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CreatedAt,
			&i.ID_2,
			&i.OfferID,
			&i.TeamID,
			&i.TeamName,
			&i.League,
			&i.TeamColor,
			&i.Icon,
			&i.PartnerName,
			&i.OfferName,
			&i.OfferDescription,
			&i.TriggerCondition,
			&i.TriggerRule,
			&i.RegionCode,
			&i.OfferUrl,
			&i.AffiliateUrl,
			&i.AffiliateTagline,
			&i.IsActive,
			&i.CreatedAt_2,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForReminder = `-- name: ListUsersForReminder :many
SELECT DISTINCT u.id, u.push_token, u.platform
FROM users u
JOIN subscriptions s ON s.user_id = u.id
JOIN triggered_events te ON te.event_id = s.event_id
LEFT JOIN dismissals d ON d.triggered_event_id = te.id AND d.user_id = u.id
LEFT JOIN notifications n ON n.user_id = u.id AND n.triggered_event_id = te.id
WHERE te.id = ?
  AND u.push_token IS NOT NULL
  AND u.push_token != ''
  AND (d.id IS NULL OR d.type != 'stop_reminding')
`

type ListUsersForReminderRow struct {
	ID        string         `json:"id"`
	PushToken sql.NullString `json:"push_token"`
	Platform  string         `json:"platform"`
}

func (q *Queries) ListUsersForReminder(ctx context.Context, id string) ([]ListUsersForReminderRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersForReminder, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForReminderRow{}
	for rows.Next() {
		var i ListUsersForReminderRow
		if err := rows.Scan(&i.ID, &i.PushToken, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithPushTokens = `-- name: ListUsersWithPushTokens :many
SELECT id, device_id, push_token, platform, created_at, updated_at, token FROM users WHERE push_token IS NOT NULL AND push_token != ''
`

func (q *Queries) ListUsersWithPushTokens(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithPushTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.PushToken,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET offer_name = ?, offer_description = ?, trigger_condition = ?, region_code = ?, is_active = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateEventParams struct {
	OfferName        string         `json:"offer_name"`
	OfferDescription string         `json:"offer_description"`
	TriggerCondition string         `json:"trigger_condition"`
	RegionCode       sql.NullString `json:"region_code"`
	IsActive         int64          `json:"is_active"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.OfferName,
		arg.OfferDescription,
		arg.TriggerCondition,
		arg.RegionCode,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications SET status = ? WHERE id = ?
`

type UpdateNotificationStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationStatus, arg.Status, arg.ID)
	return err
}

const updateUserPushToken = `-- name: UpdateUserPushToken :exec
UPDATE users SET push_token = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserPushTokenParams struct {
	PushToken sql.NullString `json:"push_token"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateUserPushToken(ctx context.Context, arg UpdateUserPushTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPushToken, arg.PushToken, arg.ID)
	return err
}
