apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freebie-scheduler.fullname" . }}
  labels:
    {{- include "freebie-scheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  worker-secret: {{ .Values.workerSecret | quote }}
