apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freebie-cloudflare.fullname" . }}
  labels:
    {{- include "freebie-cloudflare.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "freebie-cloudflare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "freebie-cloudflare.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cloudflared
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "freebie-cloudflare.fullname" . }}
                  key: tunnel-token
