apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freebie-cloudflare.fullname" . }}
  labels:
    {{- include "freebie-cloudflare.labels" . | nindent 4 }}
type: Opaque
stringData:
  tunnel-token: {{ .Values.tunnelToken | quote }}
