apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freebie-api.fullname" . }}-data
  labels:
    {{- include "freebie-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
