apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freebie-api.fullname" . }}
  labels:
    {{- include "freebie-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-path: {{ .Values.databasePath | quote }}
  worker-secret: {{ .Values.workerSecret | quote }}
