apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freebie-cronjobs.fullname" . }}
  labels:
    {{- include "freebie-cronjobs.labels" . | nindent 4 }}
type: Opaque
stringData:
  worker-secret: {{ .Values.workerSecret | quote }}
