image:
  repository: registry.digitalocean.com/freebie/freebie-api
  tag: latest
  pullPolicy: Always

api:
  serviceName: freebie-api
  port: 8080

workerSecret: ""

checkTriggers:
  schedule: "0 14 * * *"   # 7am PT (UTC-7 DST)

sendReminders:
  schedule: "0 18,22,0 * * *"  # 11am, 3pm, 5pm PT (UTC-7 DST)
