image:
  repository: registry.digitalocean.com/freebie/freebie-api
  tag: latest
  pullPolicy: IfNotPresent

api:
  serviceName: freebie-api
  port: 8080

workerSecret: ""

checkTriggers:
  schedule: "0 14 * * *"   # 6am PT (UTC-8)

sendReminders:
  schedule: "0 2 * * *"    # 6pm PT (UTC-8)
